/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicavillaframes.frames;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import java.util.*;

//import java.util.logging;
//import java.util.logging.*;
//import java.util.logging.Level;
//
//import java.util.logging.lo;

/**
 *
 * @author ale_2
 */
public class PanelAumentar extends javax.swing.JPanel {

    /**
     * Creates new form panelPrincipal
     */
    static Statement sentencia = null;
    static Datos objProduct;
    static Connection conexion = null;

    public PanelAumentar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Guardar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        letrero = new java.awt.Panel();
        ctrl_insumo = new java.awt.Label();
        PaContene = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label6 = new java.awt.Label();
        label5 = new java.awt.Label();
        label7 = new java.awt.Label();
        jPanel4 = new javax.swing.JPanel();
        JCod_medi = new javax.swing.JTextField();
        jNombreMedi = new javax.swing.JTextField();
        Jtipo_med = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jComboMeses = new javax.swing.JComboBox<>();
        JyearCad = new javax.swing.JTextField();
        Jnum_lote = new javax.swing.JTextField();
        JNum_piezas = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        btn_Guardar.setText("GUARDAR");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Guardar);

        btn_limpiar.setText("LIMPIAR");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_limpiar);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        letrero.setBackground(new java.awt.Color(255, 255, 204));
        letrero.setForeground(new java.awt.Color(0, 0, 0));

        ctrl_insumo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ctrl_insumo.setText("GUARDADO DE MEDICAMENTOS");
        letrero.add(ctrl_insumo);

        add(letrero, java.awt.BorderLayout.PAGE_START);

        PaContene.setBackground(new java.awt.Color(255, 255, 153));
        PaContene.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 10, 1));

        jPanel3.setLayout(new java.awt.GridLayout(7, 0, 0, 1));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        label1.setText("CODIGO MEDICAMENTO");
        jPanel3.add(label1);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        label2.setText("DESCRIPCION");
        jPanel3.add(label2);

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        label3.setText("TIPO");
        jPanel3.add(label3);

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        label4.setText("MES DE CADUCIDAD");
        jPanel3.add(label4);

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        label6.setText("AÑO DE CADUCIDAD");
        jPanel3.add(label6);

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        label5.setText("NUMERO LOTE");
        jPanel3.add(label5);

        label7.setAlignment(java.awt.Label.CENTER);
        label7.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        label7.setText("PIEZAS");
        jPanel3.add(label7);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(7, 0, 10, 1));

        JCod_medi.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel4.add(JCod_medi);

        jNombreMedi.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel4.add(jNombreMedi);

        Jtipo_med.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel4.add(Jtipo_med);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 0, 1));

        jComboMeses.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboMeses.setMaximumRowCount(13);
        jComboMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MES", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        jComboMeses.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMesesActionPerformed(evt);
            }
        });
        jPanel5.add(jComboMeses);

        jPanel4.add(jPanel5);

        JyearCad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel4.add(JyearCad);

        Jnum_lote.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel4.add(Jnum_lote);

        JNum_piezas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel4.add(JNum_piezas);

        jPanel2.add(jPanel4);

        javax.swing.GroupLayout PaConteneLayout = new javax.swing.GroupLayout(PaContene);
        PaContene.setLayout(PaConteneLayout);
        PaConteneLayout.setHorizontalGroup(
            PaConteneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaConteneLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addGap(101, 101, 101))
        );
        PaConteneLayout.setVerticalGroup(
            PaConteneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaConteneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        add(PaContene, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMesesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboMesesActionPerformed

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
       
        String cod_medi      =this.JCod_medi.getText();
        String nombre_medi   =this.jNombreMedi.getText();
        String tipo          =this.Jtipo_med.getText();
        String mes_cad       =this.jComboMeses.getSelectedItem().toString();
        String year_cad     = this.JyearCad.getText();
//Pasamos valores de tipo String a timpo Int 
        int year_cad2 = Integer.valueOf(year_cad);

        String cod_lote  =this.Jnum_lote.getText();
        String num_piezas  =this.JNum_piezas.getText();
//Pasamos valores de tipo String a timpo Int 
        int num_piezas2 = Integer.valueOf(num_piezas);

//llamamos ala clase de añadir datos
        conexionPostgres base=new conexionPostgres();
//añadimos

        base.insertarUsuariosAlmacen(cod_medi, nombre_medi, tipo, mes_cad, year_cad2, cod_lote, num_piezas2);        
//colocamos los datos segun este en orden de la base de datos         

    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        JCod_medi.setText("");
        jNombreMedi.setText("");
        Jtipo_med.setText("");
//        Jpa_meses.setText("");
//        jComboMeses.setToolTipText("SELECCIONE");
        JyearCad.setText("");
        Jnum_lote.setText("");
        JNum_piezas.setText("");
                
    }//GEN-LAST:event_btn_limpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JCod_medi;
    private javax.swing.JTextField JNum_piezas;
    private javax.swing.JTextField Jnum_lote;
    private javax.swing.JTextField Jtipo_med;
    private javax.swing.JTextField JyearCad;
    private javax.swing.JPanel PaContene;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_limpiar;
    private java.awt.Label ctrl_insumo;
    private javax.swing.JComboBox<String> jComboMeses;
    private javax.swing.JTextField jNombreMedi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Panel letrero;
    // End of variables declaration//GEN-END:variables
}
